/**
 * One-shot generator for src/data/europeOutline.ts.
 *
 * Reads Natural Earth 110m country polygons from the world-atlas package,
 * filters to the 42 European countries we use, projects each polygon with
 * the same equirectangular settings as src/data/coordinates.ts, and writes
 * out a static TypeScript file containing one SVG path string per country.
 *
 * Run once with:
 *   npm install -D world-atlas topojson-client
 *   node scripts/buildOutlines.mjs
 *
 * The generated file is committed to the repo; the dev dependencies above
 * are only needed at generation time and can be uninstalled afterwards.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { feature } from 'topojson-client';

// Match MAP_BOUNDS / VIEW dimensions in src/data/coordinates.ts and src/components/MapView.tsx
const MAP_BOUNDS = { minLng: -25, maxLng: 45, minLat: 35, maxLat: 70 };
const VIEW_W = 500;
const VIEW_H = 380;

// Names exactly as used in src/data/countries.ts.
const TARGET_NAMES = [
  'Albania', 'Andorra', 'Austria', 'Belarus', 'Belgium',
  'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Czech Republic',
  'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece',
  'Hungary', 'Iceland', 'Ireland', 'Italy', 'Kosovo', 'Latvia',
  'Liechtenstein', 'Lithuania', 'Luxembourg', 'Moldova', 'Monaco',
  'Montenegro', 'Netherlands', 'North Macedonia', 'Norway', 'Poland',
  'Portugal', 'Romania', 'Russia', 'San Marino', 'Serbia', 'Slovakia',
  'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'Ukraine',
  'United Kingdom',
];

// world-atlas 110m uses Natural Earth `name` properties. Map any names that
// differ from our canonical list. Anything missing here is matched on its
// natural name.
const NAME_MAP = {
  'Bosnia and Herz.': 'Bosnia and Herzegovina',
  'Czechia': 'Czech Republic',
  'Macedonia': 'North Macedonia',
  'Republic of Serbia': 'Serbia',
  'Russian Federation': 'Russia',
};

function project([lng, lat]) {
  const x = ((lng - MAP_BOUNDS.minLng) / (MAP_BOUNDS.maxLng - MAP_BOUNDS.minLng)) * VIEW_W;
  const y = ((MAP_BOUNDS.maxLat - lat) / (MAP_BOUNDS.maxLat - MAP_BOUNDS.minLat)) * VIEW_H;
  return [x, y];
}

function ringToPath(ring) {
  return ring
    .map(([lng, lat], i) => {
      const [x, y] = project([lng, lat]);
      return `${i === 0 ? 'M' : 'L'}${x.toFixed(1)},${y.toFixed(1)}`;
    })
    .join(' ') + ' Z';
}

function polygonToPath(coords) {
  // coords = [outerRing, ...holes]; SVG even-odd / nonzero handles holes.
  return coords.map(ringToPath).join(' ');
}

function geometryToPath(geom) {
  if (!geom) return '';
  if (geom.type === 'Polygon') return polygonToPath(geom.coordinates);
  if (geom.type === 'MultiPolygon') return geom.coordinates.map(polygonToPath).join(' ');
  return '';
}

const topo = JSON.parse(
  readFileSync('node_modules/world-atlas/countries-110m.json', 'utf-8')
);
const fc = feature(topo, topo.objects.countries);

const outlines = {};
const seenNames = new Set();
for (const f of fc.features) {
  const rawName = f.properties?.name ?? '';
  seenNames.add(rawName);
  const ourName = NAME_MAP[rawName] ?? rawName;
  if (!TARGET_NAMES.includes(ourName)) continue;
  outlines[ourName] = geometryToPath(f.geometry);
}

const missing = TARGET_NAMES.filter((n) => !(n in outlines));
if (missing.length) {
  console.warn('\nMissing outlines for:');
  for (const name of missing) console.warn('  -', name);
  console.warn('\nLikely-related names found in dataset:');
  const lower = (s) => s.toLowerCase();
  for (const name of missing) {
    const candidates = Array.from(seenNames).filter((n) =>
      lower(n).includes(lower(name).split(' ')[0])
    );
    if (candidates.length) {
      console.warn(`  ${name}: ${candidates.join(', ')}`);
    }
  }
}

const sortedKeys = Object.keys(outlines).sort();
const lines = [
  '// Auto-generated by scripts/buildOutlines.mjs. Do not edit by hand.',
  '// Source: Natural Earth 110m via world-atlas@2.',
  '// Each value is one or more SVG path commands projected with',
  '// MAP_BOUNDS in src/data/coordinates.ts (viewBox 500x380).',
  '',
  '/* eslint-disable */',
  'export const COUNTRY_OUTLINES: Record<string, string> = {',
];
for (const name of sortedKeys) {
  const v = outlines[name].replace(/"/g, '\\"');
  lines.push(`  ${JSON.stringify(name)}: "${v}",`);
}
lines.push('};');
lines.push('');

const outPath = 'src/data/europeOutline.ts';
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join('\n'), 'utf-8');

console.log(`\nWrote ${sortedKeys.length}/${TARGET_NAMES.length} outlines to ${outPath}.`);
